---

- name: Copying properties files to jboss4/server/default/conf
  copy: src=roles/centos-jboss4-deployment/files/RMS dest=/home/lms/jboss-4.2.3.GA/server/default/conf

- name: Copying server.xml to jboss4/server/default/deploy/jboss-web.deployer/
  template: src=roles/centos-jboss4-deployment/files/server.xml dest=/home/lms/jboss-4.2.3.GA/server/default/deploy/jboss-web.deployer/

- name: Copying the contents of {{client}}.properties to RMS.properties
  copy: src=/home/lms/jboss-4.2.3.GA/server/default/conf/RMS/{{client}}.properties  dest=/home/lms/jboss-4.2.3.GA/server/default/conf/RMS/RMS.properties remote_src=True

- name: Copying the contents of {{client}}.properties to RMS_en.properties
  copy: src=/home/lms/jboss-4.2.3.GA/server/default/conf/RMS/{{client}}_en.properties dest=/home/lms/jboss-4.2.3.GA/server/default/conf/RMS/RMS_en.properties remote_src=True


- name: Copying the contents of {{client}}.properties to RMS_fr.properties
  copy: src=/home/lms/jboss-4.2.3.GA/server/default/conf/RMS/{{client}}_fr.properties dest=/home/lms/jboss-4.2.3.GA/server/default/conf/RMS/RMS_fr.properties remote_src=True
  when: client == "Benin"

  
- name: Edit database name in LMS.properties
  lineinfile: dest=/home/lms/jboss-4.2.3.GA/server/default/conf/RMS/LMS.properties regexp={{ item.regexp }} line={{ item.line }}
  with_items:
      - { regexp: 'databaseName=*', line: 'databaseName={{rmsDatabaseName}}' }
      - { regexp: 'userName=*', line: 'userName={{rmsDatabaseUsername}}' }
      - { regexp: 'hostAddress=*', line: 'hostAddress={{rmsDatabaseHost}}' }
      - { regexp: 'password=*', line: 'password={{rmsDatabasePassword}}' }

#- name: Start the Jboss4 Server
 # command: chdir=/home/lms /bin/sh jboss4.sh
