---

     - name: Copy Jboss 1.7 to Remote Server
       get_url: url=http://192.168.126.99:8087/repository/tools/jboss-as-7.1.1.Final.tar.gz dest=/home/lms
     
     - name: Extract the Jboss tar file
       unarchive: src=/home/lms/jboss-as-7.1.1.Final.tar.gz dest=/home/lms remote_src=True

     - name: Start Jboss Server
       command: chdir=/home/lms /bin/sh jboss-start.sh
